# Generated by Django 3.2 on 2022-10-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_app'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'アカウント'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
        migrations.RemoveField(
            model_name='placephoto',
            name='image',
        ),
        migrations.AddField(
            model_name='placephoto',
            name='image1',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='placephoto',
            name='image2',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='placephoto',
            name='image3',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='placephoto',
            name='image4',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス'),
        ),
    ]
