# Generated by Django 3.2 on 2022-11-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20221031_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='lng',
            field=models.FloatField(default=None, null=True),
        ),
    ]
